language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - export FAVORITE_FOOD="$FAVORITE_FOOD"

script:
  - docker --version # print the version for logging
  - docker build -t simple-node-env --build-arg NAME=${FAVORITE_FOOD} .
  - docker tag simple-node-env isongjosiah/simple-node-env:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push isongjosiah/simple-node-env
